# Generated by Django 2.2.4 on 2020-05-05 14:18

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitive_group', to='otree.Session')),
            ],
            options={
                'db_table': 'competitive_group',
            },
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitive_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'competitive_subsession',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True)),
                ('answer_1', otree.db.models.IntegerField(null=True)),
                ('answer_2', otree.db.models.IntegerField(null=True)),
                ('answer_3', otree.db.models.IntegerField(null=True)),
                ('answer_4', otree.db.models.IntegerField(null=True)),
                ('answer_5', otree.db.models.IntegerField(null=True)),
                ('answer_6', otree.db.models.IntegerField(null=True)),
                ('answer_7', otree.db.models.IntegerField(null=True)),
                ('answer_8', otree.db.models.IntegerField(null=True)),
                ('rank', otree.db.models.IntegerField(choices=[[1, '1'], [2, '2'], [3, '3'], [4, '4']], null=True)),
                ('piece_rate_payment', otree.db.models.BooleanField(choices=[[True, '10 tokens per sum correctly answered; or'], [False, 'When all surveys are submitted, we will randomly group you with 3 other people (so you will be in a group of 4). We will compare the number of sums you correctly answer now with the number of sums the other 3 correctly answered in the previous stage you just concluded. You will be paid only if you achieve the highest number of correctly answered sums within this group, in which case you will be paid 40 tokens per sum correctly answered.']], null=True)),
                ('answer_1b', otree.db.models.IntegerField(null=True)),
                ('answer_2b', otree.db.models.IntegerField(null=True)),
                ('answer_3b', otree.db.models.IntegerField(null=True)),
                ('answer_4b', otree.db.models.IntegerField(null=True)),
                ('answer_5b', otree.db.models.IntegerField(null=True)),
                ('answer_6b', otree.db.models.IntegerField(null=True)),
                ('answer_7b', otree.db.models.IntegerField(null=True)),
                ('answer_8b', otree.db.models.IntegerField(null=True)),
                ('correct_answers_part1', otree.db.models.IntegerField(default=0, null=True)),
                ('correct_answers_part2', otree.db.models.IntegerField(default=0, null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='competitive.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitive_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitive_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitive.Subsession')),
            ],
            options={
                'db_table': 'competitive_player',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitive.Subsession'),
        ),
    ]
