# Generated by Django 2.2.4 on 2020-05-05 14:18

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiple_price_list_1_group', to='otree.Session')),
            ],
            options={
                'db_table': 'multiple_price_list_1_group',
            },
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multiple_price_list_1_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'multiple_price_list_1_subsession',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True)),
                ('winning_color_red', otree.db.models.BooleanField(choices=[[True, 'red'], [False, 'black']], null=True)),
                ('Q0_gamble', otree.db.models.BooleanField(choices=[[True, 'Urn Gamble'], [False, '0 tokens']], default=True, null=True)),
                ('Q1_gamble', otree.db.models.BooleanField(choices=[[True, 'Urn Gamble'], [False, '10 tokens']], null=True)),
                ('Q2_gamble', otree.db.models.BooleanField(choices=[[True, 'Urn Gamble          '], [False, '20 tokens']], null=True)),
                ('Q3_gamble', otree.db.models.BooleanField(choices=[[True, 'Urn Gamble'], [False, '30 tokens']], null=True)),
                ('Q4_gamble', otree.db.models.BooleanField(choices=[[True, 'Urn Gamble'], [False, '40 tokens']], null=True)),
                ('Q5_gamble', otree.db.models.BooleanField(choices=[[True, 'Urn Gamble'], [False, '50 tokens']], null=True)),
                ('Q6_gamble', otree.db.models.BooleanField(choices=[[True, 'Urn Gamble'], [False, '60 tokens']], null=True)),
                ('Q7_gamble', otree.db.models.BooleanField(choices=[[True, 'Urn Gamble'], [False, '70 tokens']], null=True)),
                ('Q8_gamble', otree.db.models.BooleanField(choices=[[True, 'Urn Gamble'], [False, '80 tokens']], null=True)),
                ('Q9_gamble', otree.db.models.BooleanField(choices=[[True, 'Urn Gamble'], [False, '90 tokens']], null=True)),
                ('Q10_gamble', otree.db.models.BooleanField(choices=[[True, 'Urn Gamble'], [False, '100 tokens']], null=True)),
                ('Q11_gamble', otree.db.models.BooleanField(choices=[[True, 'Urn Gamble'], [False, '110 tokens']], null=True)),
                ('Q12_gamble', otree.db.models.BooleanField(choices=[[True, 'Urn Gamble'], [False, '120 tokens']], null=True)),
                ('Q13_gamble', otree.db.models.BooleanField(choices=[[True, 'Urn Gamble'], [False, '130 tokens']], null=True)),
                ('Q14_gamble', otree.db.models.BooleanField(choices=[[True, 'Urn Gamble'], [False, '140 tokens']], null=True)),
                ('Q15_gamble', otree.db.models.BooleanField(choices=[[True, 'Urn Gamble'], [False, '150 tokens']], default=False, null=True)),
                ('color', otree.db.models.StringField(max_length=10000, null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='multiple_price_list_1.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiple_price_list_1_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiple_price_list_1_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multiple_price_list_1.Subsession')),
            ],
            options={
                'db_table': 'multiple_price_list_1_player',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multiple_price_list_1.Subsession'),
        ),
    ]
